name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  # 允许手动触发
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 替换为你的 HF 用户名和 Space 名称
          git push -f https://wotmlaila:$HF_TOKEN@huggingface.co/spaces/wotmlaila/metapi main
